### ISSUE TITLE
渐变+圆角怎么使用

### ISSUE THREAD

**Issue by pttyy** [xjh093/JHDraw#1]
![image](https://user-images.githubusercontent.com/13176599/68263999-73fe1000-0082-11ea-8515-d764d5f3bf08.png)
![image](https://user-images.githubusercontent.com/13176599/68264004-795b5a80-0082-11ea-8477-9fce3c88d36e.png)

上面代码 达不到下面的效果

**Comment by pttyy** [comment]
如果设置 gradientView.layer.masksToBounds = YES; 渐变色都不会有

**Comment by xjh093** [comment]
你的 gradientView 都还没设置大小吧~
